version: 2

models:
  - name: movie_performance
    description: Movie metrics and analytics generated for each movie showing
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - movie_id
            - theater_id
    columns:
      - name: movie_id
        description: Foreign key
        tests:
          - not_null
      - name: theater_id
        description: Foreign key
        tests: 
          - not_null
          
  - name: stg_movies
    description: This model cleans up movie data
    columns:
      - name: movie_id
        description: Primary key
        tests: 
          - not_null
          - unique
          - relationships:
              to: ref('movie_performance')
              field: movie_id

  - name: stg_theaters
    columns:
      - name: theater_id
        description: Primary Key
        tests: 
          - not_null
          - unique
          - relationships:
              to: ref('movie_performance')
              field: theater_id