version: 2

models:
  - name: movie_performance
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - movie_id
            - theater_id
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: theater_id
        tests: 
          - not_null
          
  - name: stg_movies
    columns:
      - name: movie_id
        tests: 
          - not_null
          - unique
          - relationships:
              to: ref('movie_performance')
              field: movie_id

  - name: stg_theaters
    columns:
      - name: theater_id
        tests: 
          - not_null
          - unique
          - relationships:
              to: ref('movie_performance')
              field: theater_id