version: 2

sources:
    - name: cinema
      description: This is a replica of a cinema database
      database: raw_2
      schema: cinema
      tables:
          - name: movies
            description: This model cleans up movie data.
          - name: theaters
            description: This model cleans up theater data.
          - name: movie_screenings
            description: Shows where and when each movie was played as well as movie metrics.

          
