version: 2

sources:
    - name: cinema
      description: This is a replica of a cinema database
      database: raw
      schema: cinema
      tables:
          - name: movies
            description: This model cleans up movie data.
          - name: cinemas
            description: This model cleans up cinema data.
          - name: customers
            description: This model cleans up customer data
          - name: tickets
            description: This model cleans us ticket data
          - name: movie_screenings
            description: Shows where and when each movie was played as well as movie metrics.

          
